server:
  port: 8081

spring:
  application:
    name: upscale
  datasource:
    username: dbuser
    password: dbuser
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postdb?currentSchema=upscale
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 180000
      idle-timeout: 60000
  flyway:
    locations: classpath:db/migration
    enabled: true
    schemas: upscale
  jpa:
    generate-ddl: false
    show-sql: true
logging:
  level:
    root: info
    org.eclipse: debug
